/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    posts: Post;
    users: User;
  };
  globals: {
    'plugin-global': PluginGlobal;
  };
}
export interface Page {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  title?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface PluginGlobal {
  id: string;
  title?: string;
  updatedAt?: string;
  createdAt?: string;
}
